---
title: "caso_itam"
author: "Roberto Ruz Campos"
date: "15/1/2020"
output:
  pagedown::html_paged:
    css: ["def-fo", "def-pg", "def"]
    toc: false
    self_contained: false
    number_sections: false
editor_options: 
  chunk_output_type: console
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(tsibble)
```

```{r}
raw_data <- read_csv(
  file = "Compustat_Global_daily.csv",
  col_types = cols(
    sedol = col_character(),
    datadate = col_date(format = "%Y%m%d")
  )
)
```

```{r}
daily_data <- raw_data %>% 
  filter(
    exchg == 208,
    curcdd %in% c("MXP", "MXN")
    ) %>% 
  mutate(
    prccd = if_else(prccd == "MXP", prccd / 1000, prccd),
    adj_price = (prccd / ajexdi) * trfd,
    mkt_cap = prccd * cshoc / 1e6,
    size = log(mkt_cap),
    month = yearmonth(datadate)
  ) %>% 
  select(
    gvkey,
    iid,
    date = datadate,
    month,
    name = conm,
    shares = cshoc,
    adj_price,
    mkt_cap,
    size
  )
```

```{r}
monthly_data <- daily_data %>% 
  group_by(gvkey, iid, month) %>% 
  summarise_all(last) %>% 
  ungroup()
```

```{r}
fundamentals <-
  read_csv(
    file = "Compustat_Fundamentals.csv",
    col_types = cols(
      gvkey = col_character(),
      datadate = col_date(format = "%Y%m%d"),
      ceqq = col_number()
    ),
    na = c("N/A", "")
  )

primary_issue <- fundamentals %>% 
  group_by(gvkey, conm) %>% 
  distinct(prirow) %>% 
  drop_na()
```

lo bueno
```{r eval=FALSE}
monthly_data %>% 
  group_by(gvkey) %>% 
  filter(
    n_distinct(iid) == 1 |
    gvkey %in% primary_issue$gvkey
  ) 

monthly_data %>% 
  group_by(gvkey) %>% 
  filter(
    n_distinct(iid) > 1,
    !gvkey %in% primary_issue$gvkey
  ) %>% 
  count(name, iid) %>% 
  print(., n = 71)

daily_data %>% 
  group_by(gvkey, iid,name) %>% 
  count() %>% 
  arrange(n) %>% 
  print(., n = 291)
```

